create table if not exists public.rsvp_responses (
  id bigint generated by default as identity primary key,
  guest_name text not null unique,
  attendance text not null check (attendance in ('hadir', 'tidak')),
  guest_count integer not null check (guest_count >= 1 and guest_count <= 20),
  responded_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_rsvp_responses_updated_at on public.rsvp_responses;
create trigger trg_rsvp_responses_updated_at
before update on public.rsvp_responses
for each row
execute function public.set_timestamp_updated_at();

alter table public.rsvp_responses enable row level security;

grant insert, update on table public.rsvp_responses to anon, authenticated;
grant usage, select on sequence public.rsvp_responses_id_seq to anon, authenticated;

drop policy if exists "public can insert rsvp" on public.rsvp_responses;
create policy "public can insert rsvp"
on public.rsvp_responses
for insert
to anon, authenticated
with check (true);

drop policy if exists "public can update rsvp" on public.rsvp_responses;
create policy "public can update rsvp"
on public.rsvp_responses
for update
to anon, authenticated
using (true)
with check (true);
